version: "3.7"

services:
  web:
    image: ${STACK_IMAGE}
    networks:
      - reverse
    # configs:
    #   - source: expires
    #     target: /etc/nginx/conf.d/expires.conf
    #   - source: gzip
    #     target: /etc/nginx/conf.d/gzip.conf
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.services.curriculum.loadBalancer.server.port=8080"
        - "traefik.http.routers.curriculum.rule=Host(`ahupond.dev`,`www.ahupond.dev`)"
        - "traefik.http.routers.curriculum.middlewares=redirect@file,secure@file"
        - "traefik.http.routers.curriculum.service=curriculum"
        - "traefik.http.routers.curriculum.tls.options=secure@file"
        - "traefik.http.routers.curriculum.tls.certResolver=gandi"      
    read_only: true
    volumes:
      - tmpfs:/tmp

networks:
  reverse:
    external: true

# configs:
#   expires:
#     file: ./expires.conf
#     name: expires-${STACK_VERSION}
#   gzip:
#     file: ./gzip.conf
#     name: gzip-${STACK_VERSION}

volumes:
  tmpfs:
    driver_opts:
      type: tmpfs
      device: tmpfs